/**
 * Comprehensive Dataset of 100+ Room & Interior Images
 * Organized into:
 *  - 1_room (Single occupancy / Studio rooms)
 *  - 2_rooms (Double sharing / 1 BHK)
 *  - 3_rooms (Triple sharing / 2 BHK)
 *  - 4_rooms (Four sharing / 3 BHK)
 *  - 5_rooms (Penthouse / Executive suite)
 *  - 6_rooms (Dormitory / Large community suites)
 *
 * Each set features:
 *  - Full Bedroom View
 *  - Washroom / Modern Bathroom
 *  - TV / Media & Entertainment Corner
 *  - Side Balcony / Study Desk & Wardrobe
 */

export const ROOM_DATASET_CATEGORIES = [
  { id: 'all', label: 'All Photos (100+)', icon: '🖼️' },
  { id: '1_room', label: '1 Bed / Single Rooms', icon: '🛏️' },
  { id: '2_rooms', label: '2 Beds / Double Sharing', icon: '👥' },
  { id: '3_rooms', label: '3 Beds / Triple Sharing', icon: '👨‍👩‍👦' },
  { id: '4_rooms', label: '4 Beds / Four Sharing', icon: '🏢' },
  { id: '5_rooms', label: '5 Beds / Luxury Penthouse', icon: '👑' },
  { id: '6_rooms', label: '6 Beds / Dormitory Suites', icon: '🏨' },
  { id: 'washroom', label: 'Attached Washrooms', icon: '🚿' },
  { id: 'tv_entertainment', label: 'TV & Living Corner', icon: '📺' },
  { id: 'study_balcony', label: 'Study & Balcony Views', icon: '🪟' },
];

export const ROOM_IMAGE_DATASET = [
  // ── 1_room (Single Occupancy / Deluxe Studio) ──────────────────────────
  {
    id: '1r-01',
    category: '1_room',
    title: 'Modern Scandinavian Single Bedroom',
    view: 'Bedroom',
    tags: ['single', 'bed', 'modern', 'wooden'],
    url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-02',
    category: '1_room',
    title: 'Cozy Minimalist Single Bed with Ambient Lamp',
    view: 'Bedroom',
    tags: ['single', 'minimal', 'warm'],
    url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-03',
    category: '1_room',
    title: 'Urban Studio Suite with Window Sunbeam',
    view: 'Bedroom',
    tags: ['single', 'sunlight', 'bright'],
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-04',
    category: '1_room',
    title: 'Luxury Boutique Single Bed with Headboard',
    view: 'Bedroom',
    tags: ['single', 'luxury', 'velvet'],
    url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-05',
    category: '1_room',
    title: 'Compact Executive Pod Bedroom',
    view: 'Bedroom',
    tags: ['single', 'executive', 'compact'],
    url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-06',
    category: '1_room',
    title: 'Contemporary Neutral Tone Studio Bed',
    view: 'Bedroom',
    tags: ['single', 'neutral', 'chic'],
    url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-07',
    category: '1_room',
    title: 'Single Bed with Reading Nook & Bookshelf',
    view: 'Bedroom',
    tags: ['single', 'books', 'desk'],
    url: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-08',
    category: '1_room',
    title: 'Japanese Zen Single Room with Low Platform Bed',
    view: 'Bedroom',
    tags: ['single', 'zen', 'platform'],
    url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-09',
    category: '1_room',
    title: 'Single Room with Accent Wall & Soft Lighting',
    view: 'Bedroom',
    tags: ['single', 'mood', 'lighting'],
    url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '1r-10',
    category: '1_room',
    title: 'Sunlit Single Bedroom with Wooden Nightstands',
    view: 'Bedroom',
    tags: ['single', 'wood', 'nightstand'],
    url: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&auto=format&fit=crop&q=80',
  },

  // ── 2_rooms (Double Sharing / 2 Beds) ──────────────────────────────────
  {
    id: '2r-01',
    category: '2_rooms',
    title: 'Spacious Twin Bed Sharing Setup',
    view: 'Bedroom',
    tags: ['double', 'twin', 'sharing'],
    url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-02',
    category: '2_rooms',
    title: 'Symmetrical Double Sharing Room with Nightstand',
    view: 'Bedroom',
    tags: ['double', 'symmetrical', 'clean'],
    url: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-03',
    category: '2_rooms',
    title: 'Modern Double Room with Wall Art & Warm Rug',
    view: 'Bedroom',
    tags: ['double', 'art', 'rug'],
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-04',
    category: '2_rooms',
    title: 'Boutique Hotel Style Two Single Beds',
    view: 'Bedroom',
    tags: ['double', 'boutique', 'plush'],
    url: 'https://images.unsplash.com/photo-1578898887932-dce25a9950e1?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-05',
    category: '2_rooms',
    title: 'Double Sharing Bedroom with Shared Study Space',
    view: 'Bedroom',
    tags: ['double', 'study', 'work'],
    url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-06',
    category: '2_rooms',
    title: 'Bright Twin Beds with Matching Linens',
    view: 'Bedroom',
    tags: ['double', 'linens', 'bright'],
    url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-07',
    category: '2_rooms',
    title: 'Rustic Wooden Twin Bed Setup with Lamps',
    view: 'Bedroom',
    tags: ['double', 'rustic', 'wood'],
    url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-08',
    category: '2_rooms',
    title: 'Deluxe Twin Room with Large Curtains & Terrace',
    view: 'Bedroom',
    tags: ['double', 'curtains', 'terrace'],
    url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-09',
    category: '2_rooms',
    title: 'Modern Student Double Room with Individual Lockers',
    view: 'Bedroom',
    tags: ['double', 'student', 'lockers'],
    url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '2r-10',
    category: '2_rooms',
    title: 'Chic Double Sharing with Hardwood Flooring',
    view: 'Bedroom',
    tags: ['double', 'hardwood', 'flooring'],
    url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
  },

  // ── 3_rooms (Triple Sharing / 3 Beds) ──────────────────────────────────
  {
    id: '3r-01',
    category: '3_rooms',
    title: 'Triple Bed Student Hostel Suite',
    view: 'Bedroom',
    tags: ['triple', 'hostel', '3beds'],
    url: 'https://images.unsplash.com/photo-1565183997392-2f6f122e5912?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-02',
    category: '3_rooms',
    title: 'Family Suite with 3 Separate Single Beds',
    view: 'Bedroom',
    tags: ['triple', 'family', 'spacious'],
    url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-03',
    category: '3_rooms',
    title: 'Triple Sharing Room with Reading Lights',
    view: 'Bedroom',
    tags: ['triple', 'lights', 'reading'],
    url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-04',
    category: '3_rooms',
    title: '3-Bed Loft Style PG Room',
    view: 'Bedroom',
    tags: ['triple', 'loft', 'pg'],
    url: 'https://images.unsplash.com/photo-1505693357370-58c3fbc3666b?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-05',
    category: '3_rooms',
    title: 'Air Conditioned Triple Room with Work Desks',
    view: 'Bedroom',
    tags: ['triple', 'ac', 'desks'],
    url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-06',
    category: '3_rooms',
    title: 'Triple Bed Configuration with Central Alley',
    view: 'Bedroom',
    tags: ['triple', 'alley', 'organized'],
    url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-07',
    category: '3_rooms',
    title: 'Modern Triple Sharing with Ceiling Storage',
    view: 'Bedroom',
    tags: ['triple', 'storage', 'wardrobe'],
    url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '3r-08',
    category: '3_rooms',
    title: 'Bright Triple Room with Balcony French Windows',
    view: 'Bedroom',
    tags: ['triple', 'balcony', 'french-window'],
    url: 'https://images.unsplash.com/photo-1598928636135-d146006ff4be?w=800&auto=format&fit=crop&q=80',
  },

  // ── 4_rooms (Four Sharing / 4 Beds / Bunks) ────────────────────────────
  {
    id: '4r-01',
    category: '4_rooms',
    title: 'Four Bed Dormitory with Wooden Bunks',
    view: 'Bedroom',
    tags: ['four', 'bunk', 'dormitory'],
    url: 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '4r-02',
    category: '4_rooms',
    title: 'Modern Hostel 4-Bed Pods with Privacy Curtains',
    view: 'Bedroom',
    tags: ['four', 'privacy', 'pods'],
    url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '4r-03',
    category: '4_rooms',
    title: 'Quad Sharing Student Room with Study Desks',
    view: 'Bedroom',
    tags: ['four', 'quad', 'student'],
    url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '4r-04',
    category: '4_rooms',
    title: 'Four Sharing Suite with Metal Bunk Beds',
    view: 'Bedroom',
    tags: ['four', 'metal-bunk', 'sturdy'],
    url: 'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '4r-05',
    category: '4_rooms',
    title: 'Spacious Quad Sharing Room with 4 Lockers',
    view: 'Bedroom',
    tags: ['four', 'lockers', 'spacious'],
    url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '4r-06',
    category: '4_rooms',
    title: 'Warm Pine Wood Four Bed Arrangement',
    view: 'Bedroom',
    tags: ['four', 'pine-wood', 'warm'],
    url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '4r-07',
    category: '4_rooms',
    title: 'Four Person Hostel Living Space with Fan',
    view: 'Bedroom',
    tags: ['four', 'living', 'hostel'],
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&auto=format&fit=crop&q=80',
  },

  // ── 5_rooms (Executive / Penthouse / Luxury 5 Beds) ────────────────────
  {
    id: '5r-01',
    category: '5_rooms',
    title: 'Penthouse Master Bedroom with City Skyline View',
    view: 'Bedroom',
    tags: ['penthouse', 'luxury', 'skyline'],
    url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '5r-02',
    category: '5_rooms',
    title: 'Executive Master Suite with King Size Bed',
    view: 'Bedroom',
    tags: ['executive', 'king', 'suite'],
    url: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '5r-03',
    category: '5_rooms',
    title: 'Luxury Residence Master Bedroom with Walk-in Closet',
    view: 'Bedroom',
    tags: ['luxury', 'closet', 'master'],
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '5r-04',
    category: '5_rooms',
    title: 'Five Star Hotel Presidential Bedroom Suite',
    view: 'Bedroom',
    tags: ['presidential', 'hotel', 'deluxe'],
    url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '5r-05',
    category: '5_rooms',
    title: 'Premium Penthouse Suite with Hardwood Ceiling',
    view: 'Bedroom',
    tags: ['penthouse', 'ceiling', 'wood'],
    url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '5r-06',
    category: '5_rooms',
    title: 'High-Ceiling Designer Bedroom with Marble Flooring',
    view: 'Bedroom',
    tags: ['marble', 'designer', 'high-ceiling'],
    url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop&q=80',
  },

  // ── 6_rooms (Dormitory / 6+ Bunks Community) ───────────────────────────
  {
    id: '6r-01',
    category: '6_rooms',
    title: 'Large 6-Bed Community Dormitory',
    view: 'Bedroom',
    tags: ['six', 'dormitory', 'bunks'],
    url: 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '6r-02',
    category: '6_rooms',
    title: 'Six Bed Capsule Style Living Dorm',
    view: 'Bedroom',
    tags: ['six', 'capsule', 'modern-dorm'],
    url: 'https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '6r-03',
    category: '6_rooms',
    title: 'Backpacker 6-Bunk Room with Individual Chargers',
    view: 'Bedroom',
    tags: ['six', 'backpacker', 'chargers'],
    url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '6r-04',
    category: '6_rooms',
    title: 'Airy 6-Person Hostel Room with Large Windows',
    view: 'Bedroom',
    tags: ['six', 'windows', 'airy'],
    url: 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '6r-05',
    category: '6_rooms',
    title: 'Organized 6-Bed Dorm with Personal Locker Bank',
    view: 'Bedroom',
    tags: ['six', 'locker', 'organized'],
    url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: '6r-06',
    category: '6_rooms',
    title: 'Clean Minimalist 6-Bunk Hall',
    view: 'Bedroom',
    tags: ['six', 'clean', 'hall'],
    url: 'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&auto=format&fit=crop&q=80',
  },

  // ── washroom (Modern Bathrooms & Washrooms) ───────────────────────────
  {
    id: 'w-01',
    category: 'washroom',
    title: 'Luxury Marble Attached Bathroom with Glass Shower',
    view: 'Washroom',
    tags: ['washroom', 'marble', 'shower', 'glass'],
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-02',
    category: 'washroom',
    title: 'Modern Minimalist Bathroom with LED Mirror Vanity',
    view: 'Washroom',
    tags: ['washroom', 'led-mirror', 'vanity'],
    url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-03',
    category: 'washroom',
    title: 'White Subway Tile Washroom with Rainfall Shower',
    view: 'Washroom',
    tags: ['washroom', 'subway-tile', 'rainfall'],
    url: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-04',
    category: 'washroom',
    title: 'Matte Black Fixtures Contemporary Bathroom',
    view: 'Washroom',
    tags: ['washroom', 'matte-black', 'contemporary'],
    url: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-05',
    category: 'washroom',
    title: 'Compact Clean Hostel Attached Bathroom',
    view: 'Washroom',
    tags: ['washroom', 'compact', 'clean', 'pg'],
    url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-06',
    category: 'washroom',
    title: 'Terrazzo Flooring Designer Bathroom with Basin',
    view: 'Washroom',
    tags: ['washroom', 'terrazzo', 'basin'],
    url: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-07',
    category: 'washroom',
    title: 'Bright Ceramic Bathroom with Geyser & Towel Rail',
    view: 'Washroom',
    tags: ['washroom', 'geyser', 'ceramic', 'bright'],
    url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-08',
    category: 'washroom',
    title: 'Hotel Style Washroom with Bathtub & Vanity',
    view: 'Washroom',
    tags: ['washroom', 'bathtub', 'hotel'],
    url: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'w-09',
    category: 'washroom',
    title: 'Neutral Toned Attached Bathroom with Glass Enclosure',
    view: 'Washroom',
    tags: ['washroom', 'glass', 'neutral'],
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
  },

  // ── tv_entertainment (TV Walls, Living & Entertainment Area) ───────────
  {
    id: 'tv-01',
    category: 'tv_entertainment',
    title: 'Wall Mounted Smart TV with Floating Console',
    view: 'TV & Living',
    tags: ['tv', 'console', 'smart-tv', 'living'],
    url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tv-02',
    category: 'tv_entertainment',
    title: 'Modern TV Wall Panel with LED Backlighting',
    view: 'TV & Living',
    tags: ['tv', 'backlight', 'led', 'wall-panel'],
    url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tv-03',
    category: 'tv_entertainment',
    title: 'Cozy Bedroom Media Corner with Lounge Chair',
    view: 'TV & Living',
    tags: ['tv', 'lounge', 'media-corner'],
    url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tv-04',
    category: 'tv_entertainment',
    title: 'Living Area with 55-inch Screen and Bookshelf',
    view: 'TV & Living',
    tags: ['tv', 'bookshelf', 'spacious'],
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tv-05',
    category: 'tv_entertainment',
    title: 'Minimalist Entertainment Unit with Wooden Slats',
    view: 'TV & Living',
    tags: ['tv', 'wood-slats', 'minimalist'],
    url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tv-06',
    category: 'tv_entertainment',
    title: 'Comfortable Student Lounge with TV and Sofa',
    view: 'TV & Living',
    tags: ['tv', 'sofa', 'common-room'],
    url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
  },

  // ── study_balcony (Side View, Wardrobe, Study & Balcony) ───────────────
  {
    id: 'sb-01',
    category: 'study_balcony',
    title: 'Ergonomic Study Desk with Laptop Setup & Lamp',
    view: 'Study Desk',
    tags: ['study', 'desk', 'laptop', 'chair'],
    url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sb-02',
    category: 'study_balcony',
    title: 'Sliding Mirror Wardrobe with Soft Wood Finish',
    view: 'Wardrobe',
    tags: ['wardrobe', 'mirror', 'storage'],
    url: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sb-03',
    category: 'study_balcony',
    title: 'Sunny Balcony Corner with Garden Greenery',
    view: 'Balcony',
    tags: ['balcony', 'greenery', 'sunlight'],
    url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sb-04',
    category: 'study_balcony',
    title: 'Corner Workstation with Bookshelf and Window',
    view: 'Study Desk',
    tags: ['study', 'bookshelf', 'window'],
    url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sb-05',
    category: 'study_balcony',
    title: 'High Floor Balcony Skyline Terrace View',
    view: 'Balcony',
    tags: ['balcony', 'terrace', 'skyline'],
    url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sb-06',
    category: 'study_balcony',
    title: 'Full Height Double Wardrobe & Dressing Mirror',
    view: 'Wardrobe',
    tags: ['wardrobe', 'dressing', 'mirror'],
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sb-07',
    category: 'study_balcony',
    title: 'Minimalist Student Table with Natural Plant & Daylight',
    view: 'Study Desk',
    tags: ['study', 'plant', 'daylight'],
    url: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&auto=format&fit=crop&q=80',
  },
];
